<?php

namespace App\Controller\Admin;

use App\Entity\ClinicalRotationCategory;
use App\Entity\Enrolment;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;

class EnrolmentCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Enrolment::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Créneau d\'urgence')
            ->setEntityLabelInPlural('Créneaux')
            ->setPaginatorPageSize(30)
            ;
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id', 'ID')->setPermission('ROLE_SUPER_ADMIN')->hideWhenCreating(),
            DateField::new('date', 'Date'),
            AssociationField::new('clinicalRotationCategory', 'Catégorie de garde'),
            AssociationField::new('student', 'Étudiant' )->autocomplete(),
        ];
    }

    public function configureActions(Actions $actions): Actions
    {
        return parent::configureActions($actions); // TODO: Change the autogenerated stub
    }
}
